# Generated by Django 3.2.6 on 2021-08-12 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('companyName', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('experience', models.CharField(blank=True, max_length=150, null=True)),
                ('salary', models.CharField(blank=True, max_length=150, null=True)),
                ('vacancy', models.CharField(blank=True, max_length=150, null=True)),
                ('employmentStatus', models.CharField(blank=True, max_length=150, null=True)),
                ('jobResponsibilities', models.CharField(blank=True, max_length=150, null=True)),
                ('additionalRequirements', models.CharField(blank=True, max_length=150, null=True)),
                ('benefits', models.CharField(blank=True, max_length=150, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('categories', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.categorey')),
            ],
        ),
    ]
