# Generated by Django 3.2.6 on 2021-08-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210812_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='categories',
        ),
        migrations.AddField(
            model_name='job',
            name='categories',
            field=models.ManyToManyField(to='jobs.Categorey'),
        ),
    ]
