# Generated by Django 3.2.6 on 2021-08-12 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210812_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='categories',
        ),
        migrations.AddField(
            model_name='job',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.categorey'),
            preserve_default=False,
        ),
    ]
