# Generated by Django 3.2.6 on 2021-08-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20210812_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='vacancy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
