# Generated by Django 3.2.6 on 2021-08-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
    ]
