# Generated by Django 3.2.6 on 2021-08-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_job_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobContext',
            field=models.TextField(blank=True, null=True),
        ),
    ]
